version: ~> 1.0

env:
  global:
    # Doctr deploy key for pcdshub/pcdswidgets
    - secure: "ZpbEFHUMVvNorSL19HMT7MD7D4/0q3tk3uyeNqzfVQE0tH0RM437AApZEQ35C4ndKeu97s9uY+Ajs9jfy1N2d/HcApP+n33EX+ufdPbYIL/7eUJnU8yu7paWII1oka76gkQMrJJvVhLzhDa5JtUhs/WR6LmBmYMucKRXaN9UFpwQ13WmNxbHEd71TyY4eYRhq4CNR0JYXKPcl7qVEt3GJ8OG9s71qamyBbCdkZFOylbcKJ0PVVi9OX/UrDarRBQgN7XmUptHocED6kjvmrhjqxg4aZ5c8v+9t00o8dMxHTXituuadcGDhYuic8ZVLm0v6dZxH7fK1hgXxY9t0gWvYv/PSIN7FME5tU9DcTfC36UtMCN5Jkz1ohH5PSJ2AeTeM/akfeiTxusQWrqIWNt32i8HlZvqtUK3Iss9SGQIrgGeusu5S4TqjUb6hgbkDlQmpZ3KqOcoRk/8rBKIfOoqJSs3m5qg0v5Zz95V07K+wsTNuMO0Zb5El+BCHcLGIFleu+m73qxJ1byz0sQhcqAaUt3y3kzxIwOYSOqYJQLCIHXnnFZyIcow6KJZQYO2ib78fpZmNoeXjoO2rA9ZziJuU/nyKKQncJSdKEAplUFG2Uir9r0aRitCsfjtgrUh9fj/n3OXOas8gS0VJ+F4SQUkrhgSwOsFilB4xzHeGYNz/i0="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="pcdswidgets"

    # The name of the conda package
    - CONDA_PACKAGE="pcdswidgets"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip pyqt=5"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS="PyQt5"

# Uncomment this block if you would like to make the Python PIP test an allowed
# failure
jobs:
  allow_failures:
    # This makes the PIP based Python 3.6 optional for passing.
    # Remove this block if passing tests with PIP is mandatory for your
    # package
    - name: "Python 3.6 - PIP"

import:
  # If your project requires X11 leave the following import
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
