{% set data = load_setup_py_data() %}

package:
    name: pcdswidgets
    version: {{ data.get('version') }}

source:
    path: ..

build:
    noarch: python

requirements:
    build:
      - python >=3.7
      - setuptools
    run:
      - python >=3.7
      - pydm >=1.9.0
      - qtpy

test:
    imports:
      - pcdswidgets
    requires: 
      - pytest

about:
  home: https://github.com/pcdshub/pcdswidgets
  license: SLAC Open License
  summary: LCLS PyDM Widget Library
